### ISSUE TITLE
Matterbridge update changed HomeKit setup

### ISSUE THREAD

**Issue by twocolddogs** [Luligu/matterbridge#109]
Updated from 1.4.1 to 1.4.3 and all my Shelly's are now either renamed or assigned to the wrong room. 

Will have to remove matterbridge-Shelly again and reinstall...

**Comment by twocolddogs** [comment]
Ok. After a couple of restarts and resetstoragediscover things are better. Had a couple of devices that were missing come back 

All the icon customisation in HomeKit have gone though 

Also, in the matterbridge logs I've got an orphaned device which now has a new IP but matterbridge keeps thinking it's offline

**Comment by Lanstrom** [comment]
Just had the same thing happen in my Google Home setup.  Everything disappeared for a minute and the suddenly came back as new devices with unassigned rooms.

**Comment by twocolddogs** [comment]
I've gone through and assigned static IPs to all my Shelly's then did a resetStorageDiscover.

So far seems to be running smoothly with everything working as expected again.

**Comment by Luligu** [comment]
Hi,
I'm glad you sorted it out.
But I would like to understand the first issue (update to 1.4.3): can you tell how you run matterbridge and on what machine?
Cause out deployment policy includes updates and checks on new setup and existing setup and that never happened.
Is it possible that the shelly plugin was late to load and when it loaded the HomeKit already saw that the devices were no more in bridge? I guess this what can happens if there are issues on the plugin. 

For the static address: @tammeryousef1006 uses static too to keep them stable, I just use dhcp and my router keep them stable too. For sure if they change address you find yourself in a situation where 1 you need to reset the storage and 2 HomeKit will temporarily remove all devices and so reset them (names, rooms, automation). 

If that is the issue you encountered we can evaluate to do:
1) we modify shelly plugin with a "safeCount" option that put the plugin in error mode so the bridge doesn't start when you don't have all your devices. 
2) we can add some warning that advise you that your devices have changed  ip.

HomeKit is best Matter controller so far but an app that makes a backup of names rooms and automations can be really good to have.

Thanks again.

**Comment by Luligu** [comment]
> Just had the same thing happen in my Google Home setup. Everything disappeared for a minute and then suddenly came back as new devices with unassigned rooms.

Hi,
can you tell me too how you run matterbridge and on what machine? Do you use shelly ?

Google is also respecting the Matter specifications, so when a device is removed from the bridge, it is deleted from the Home too.

Same solutions for you as for @twocolddogs.

Let me know.

Thanks.

**Comment by Lanstrom** [comment]
> > Just had the same thing happen in my Google Home setup. Everything disappeared for a minute and then suddenly came back as new devices with unassigned rooms.
> 
> Hi, can you tell me too how you run matterbridge and on what machine? Do you use shelly ?
> 
> Google is also respecting the Matter specifications, so when a device is removed from the bridge, it is deleted from the Home too.
> 
> Same solutions for you as for @twocolddogs.
> 
> Let me know.
> 
> Thanks.

Hi

I use Matterbridge in a docker (running on pi4).  I just take the container down and it starts back up after grabbing the latest image.

I have 3x ZigBee (generic) smart sockets and also some virtual switches which are all pulled from Home Assistant.

All the devices disappeared from Google Home but then a minute later my mobile and tablet popped up a dialogue box announcing that new devices had been found. 

Cheers.

**Comment by Luligu** [comment]
Can you send me the link to the package you use for "virtual switches which are all pulled from Home Assistant", I will take a look.

**Comment by twocolddogs** [comment]
Hi @Luligu 

Had a perfect update this morning to 1.5.1 and 0.9.2

**Comment by Luligu** [comment]
I'm glad to know that!

I appreciate the feedback.

My best

**Comment by Luligu** [comment]
## [1.5.2] - 2024-08-30

### Added

- [frontend]: Added a confirmation message to remove plugin and disable plugin.

### Changed

- [package]: Update dependencies.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by lennremy** [comment]
I just had the same problem when updating matterbridge from 1.6.1 to 1.6.2.

I'm running the Home Assistant plugin and after the update all connected devices appeared as new devices in the home app.
