### ISSUE TITLE
Reconnection issue with Alexa and 3 interfaces

### ISSUE THREAD

**Issue by viama** [Luligu/matterbridge#128]
Hello,

I am running Matterbridge v1.5.5 and the v2.1.16 z2m plugin in the docker container, and have been facing an issue with the container exiting with exit code 1.  I've been getting Alexa to consume the fabric as a test, but I'd like to add Google Home at some point. I have 87 devices exposed at the moment, having filtered out some of the >100 I have.

The container restarts as configured, but it's apparent that all of the devices are then rediscovered by Alexa.

I've attached the logs from the container:
[_ha_matterbridge.1.03k0sun2a23p52k3flieemt5b_logs.txt](https://github.com/user-attachments/files/16978470/_ha_matterbridge.1.03k0sun2a23p52k3flieemt5b_logs.txt)

Thanks for a great project

**Comment by Luligu** [comment]
Hi,
first of all thanks for your appreciation.
I need the full log from start to at least 10 minutes. So please leave the log level to debug and log on file on for both Matterbridge and Matter,
restart, wait a few minutes then download both logs and send them.

**Comment by Apollon77** [comment]
Also out of interest: @viama how many Alexa/Echo devices you have in your network?

**Comment by Apollon77** [comment]
I think you need to wait longer ... this is just the start of the matterbridge... no echo did yet connected at all, so bridge was also not crashing :-) ideally get debug log from start till crash

**Comment by Apollon77** [comment]
PS: The log is just interesting in a way that it added NEW endpoints for all the devices, so as if the bridge was configured freshly

**Comment by viama** [comment]
[matter.log](https://github.com/user-attachments/files/16983870/matter.log)
[matterbridge.log](https://github.com/user-attachments/files/16983871/matterbridge.log)
Please try these, it hasn't crashed since 1500 UK odd.

Yes, the network is a little funky. I'm using a small Dell Wyse 7060 to run HA, and that's where matterbridge is running too. I use a macvlan interface in docker swarm for stuff like this that needs to do mDNS / broadcast stuff. I have been considering moving matterbridge to another docker host thats a bit more straightforward (not swarm!)

cheers

**Comment by Apollon77** [comment]
In fact the crash reason of initial log I already found and will fix in a next matter.js version and it should be special case because he was not able to find any communication channel, so likely it was something strange with the network. 

When looking at the log I see again ew endpoint ids got assigned which is all strange beause that way the bridge is always new so also Alexa needs to reinit all devices on each start and would also loose all routines ... so thats tsrange and shuld be checked @Luligu  ... likely this is also a reason for "that many stuff" going on here on start because alexa needs to throw away all devices and re-learn them.

I still need to look into that log deeper because stuff is happening tat I can not understand currently ... there are issues with sending subscription updates and this leads to a constantly resubscribes which costs a lot of traffic ...

**Comment by viama** [comment]
I have moved the container to a simpler host for a stability test, I'll let you know if I have any issues. I can shift it back again if you need me to test anything.

**Comment by Apollon77** [comment]
Why you renamed the issue? There are no commissioning issues here ... it is just reconnection issues with Alexa. In fact I found the reasons why the crash happened and one more thing I saw in the log. Why alexa reconnects basically every hour I do not know :)

**Comment by Luligu** [comment]
> I have moved the container to a simpler host for a stability test, I'll let you know if I have any issues. I can shift it back again if you need me to test anything.

Did you try before to use mdns interface to limit matter mdns?
Was it useful?

**Comment by viama** [comment]
> > I have moved the container to a simpler host for a stability test, I'll let you know if I have any issues. I can shift it back again if you need me to test anything.
> 
> Did you try before to use mdns interface to limit matter mdns? Was it useful?

yes, it didn't help, I limited the interfaces and has the same issue.

**Comment by Luligu** [comment]
Hi,
@Apollon77 published a fix in 0.10.3.
I updated the dev now.
Can you please try to use the dev instead of the latest from docker hub and let us know?
I'm interested also about any other observations from you about the dev cause is on Debian 12 with node 22 ( @tammeryousef1006  and I are testing it since a while before moving also the latest to Debian 12 and node 22).
Thank you.

**Comment by Luligu** [comment]
@viama can I close this issue?
Cause matter.js is 0.10.6 and matterbridge is 1.5.9 so all is a little too old.

**Comment by viama** [comment]
Working well for me now, but did move to a single interfaced machine
