### ISSUE TITLE
OpenThread Border Router

### ISSUE THREAD

**Issue by Slyke** [Luligu/matterbridge#155]
Hello, is MatterBridge compatible with [OpenThread Border Router](https://github.com/openthread/openthread)?

Would be happy if anyone else knows of a docker image that can run Thread.

I flashed a nRF52840 with custom firmware that's compatible with OTBR (OpenThread Border Router) and setup a Thread network, but having difficulty figuring out how to get MatterBridge to talk to it so I can get Thread devices using Matter.

**Comment by Apollon77** [comment]
I think you misunderstand Matterbridge right now ... It is creating a device bridge, it is (at least not currently) a controller that can control other devices. And in fact with an OTBR other bevices do not need to "speak" Thread itself because the BR is your "thread to IPv6 bridge", so all others wotk on IPv6

**Comment by Luligu** [comment]
Hi,
it is still just an idea I have to write a plugin that connect to single matter devices and bring them together in the bridge.

**Comment by Slyke** [comment]
Awesome! Yeah, I didn't mean a full DHCP/Commissioner or anything like that, haha. I use the the standalone Python-Matter-Server for that.
