### ISSUE TITLE
Plugins break when docker compose recreates container

### ISSUE THREAD

**Issue by Ultra-bob** [Luligu/matterbridge#76]
When docker compose recreates my container (for example after editing the environment variables or command), the plugins break, seemingly because the `node_modules` folder was reset

```yaml
  matterbridge:
    environment:
      HOME_ASSISTANT_URL: 'http://192.168.2.4:8123'
      HOME_ASSISTANT_ACCESS_TOKEN: "*********"
      HOME_ASSISTANT_CLIENT_CONFIG: |
        {
          "includeDomains": ["light", "fan"],
          "includePatterns": ["switch.sound_machine", "binary_sensor.*_door"]
        }
    container_name: matterbridge
    command: ["matterbridge", "-bridge", "-docker", "-mdnsinterface eno1"]
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - "${HOME}/homeassistant/config/matterbridge/plugins:/root/Matterbridge" # Mounts the Matterbridge plugin directory
      - "${HOME}/homeassistant/config/matterbridge/storage:/root/.matterbridge" # Mounts the Matterbridge storage directory
```

Error logs:

```
[00:10:35.749] [Matterbridge] Matterbridge version 1.3.9 mode bridge restart mode docker running on Linux 6.1.0-21-amd64 linux x64 
[00:10:35.818] [Matterbridge] The frontend http server is listening on http://172.19.0.1:8283 
[00:10:35.819] [Matterbridge] The WebSocketServer is listening on ws://172.19.0.1:8283 
[00:10:35.826] [Matterbridge] Loading plugin matterbridge-home-assistant type DynamicPlatform 
[00:10:35.829] [Matterbridge] Failed to load plugin matterbridge-home-assistant: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/matterbridge-home-assistant/package.json' 
[00:10:36.376] [Matterbridge] The plugin matterbridge-home-assistant is up to date. Current version: 1.5.2, Latest version: 1.5.2 
[00:10:36.827] [Matterbridge] The plugin matterbridge-home-assistant is in error state. 
[00:10:36.827] [Matterbridge] The bridge will not start until the problem is solved to prevent the controllers from deleting all registered devices. 
[00:10:36.827] [Matterbridge] If you want to start the bridge disable the plugin in error state and restart. 
```

**Comment by Ultra-bob** [comment]
The only way I was able to work around it was to hit remove and then re-install it every time this happened

**Comment by Luligu** [comment]
Hi,
the reason is simple:
- on the matterbridge docker hub image there is not only matterbridge@latest but also all the plugins@latest;
- there is not of course matterbridge-home-assistant and so it is not found anymore in the container.

Solutions:
- they ask me to add matterbridge-home-assistant in the matterbridge image;
- I try to refactor the code in this way: when Matterbridge loads and a plugin is registered but not found anymore (it happens only inside docker) then Matterbridge will try to reinstall it.

P.S.: Is "-mdnsinterface eno1" working correctly ?

**Comment by Luligu** [comment]
> The only way I was able to work around it was to hit remove and then re-install it every time this happened

Try to just install it, I didn't try but I guess it should work.

**Comment by Ultra-bob** [comment]
> P.S.: Is "-mdnsinterface eno1" working correctly ?
It seems to work, no more errors

> they ask me to add matterbridge-home-assistant in the matterbridge image;
I'll try using the matterbridge-home-assistant docker image instead of this one

**Comment by Ultra-bob** [comment]
That seems to solve my problem

**Comment by Luligu** [comment]
## [1.3.10] - 2024-07-05

### Added

- [fabrics]: Added fabricInfo to matterbridge in bridge mode and to the plugins in childbridge mode.
- [sessions]: Added sessionInfo to matterbridge in bridge mode and to the plugins in childbridge mode.
- [frontend]: Added fabricInfo in bridge mode and in childbridge mode instead of QRCode if already paired.
- [frontend]: Added sessionInfo in bridge mode and in childbridge mode instead of QRCode if already paired.
- [matterbridge]: Added parsePlugin to load the updated data from the plugin even when is disabled.
- [matterbridge]: Added an automatic plugin reinstall from npm when the plugin is not found. (e.g. when the docker image is updated and the plugin is not an official plugin)

### Changed

- [dependencies]: Update dependencies.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

This solve the problem of reinstalling npm plugins after docker pull.
